### ISSUE TITLE
badFingerprints.includes is not a function

### ISSUE THREAD

**Issue by holdsworth** [bbondy/abp-filter-parser#11]
I am trying to run your module and I get this error, I will try to fix it however if you are available and have a quick fix in mind that could be really nice..

_badFingerprintsJs.badFingerprints is an array and doesn't have the prototype function includes, if you could tell me what it does maybe I could write a polyfill for it.

TypeError: _badFingerprintsJs.badFingerprints.includes is not a function
    at _loop (/path/to/node/node_modules/abp-filter-parser/dist/src/abp-filter-parser.js:617:59)
    at getFingerprint (/path/to/node/node_modules/abp-filter-parser/dist/src/abp-filter-parser.js:628:21)
    at parseFilter (/path/to/node/node_modules/abp-filter-parser/dist/src/abp-filter-parser.js:232:23)
    at Object.parse (/path/to/node/node_modules/abp-filter-parser/dist/src/abp-filter-parser.js:266:11)
    at Object.<anonymous> (/path/to/node/MyScript.js:23:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

Thanks

**Comment by holdsworth** [comment]
test]# npm test

> abp-filter-parser@0.2.0 test (/path/to/node/node_modules/abp-filter                                                                                                             -parser
> mocha --compilers js:babel/register

  options#parseOptions()
    ✓ Option parsing should split options properly
    ✓ domain rule types should be properly parsed
    ✓ parseFilter for full rules properly extracts options

  parser#parseFilter()
    ✓ should extract proper parsing info for filter rules
    ✓ Exception tests work correctly
    ✓ Option and param context rules work correctly

  parser#parse()
    1) should parse EasyList without failing
    ✓ Calling parse amongst 2 different lists should preserve both sets of rules

  rule-types#parse()
    ✓ rule types should be properly detected

  8 passing (2s)
  1 failing

  1) parser#parse() should parse EasyList without failing:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call                                                                                                             ed in this test.
      at test/parser-test.js:442:7
      at tryToString (fs.js:414:3)
      at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:401:12)

npm ERR! Test failed.  See above for more details.

Test added here ^

**Comment by hackable** [comment]
require('babel-polyfill');

fixes the problem

**Comment by bbondy** [comment]
pls submit a PR.  I think at the time I was using babel-node instead.

**Comment by hackable** [comment]
Have added fix using polyfill #13 you could merge it
